font:
  normal:
    family: "FiraCode Nerd Font"

schemes:
  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    normal:
      black:    '0x3B4252'
      red:      '0xBF616A'
      green:    '0xA3BE8C'
      yellow:   '0xEBCB8B'
      blue:     '0x81A1C1'
      magenta:  '0xB48EAD'
      cyan:     '0x88C0D0'
      white:    '0xE5E9F0'
    bright:
      black:    '0x4C566A'
      red:      '0xBF616A'
      green:    '0xA3BE8C'
      yellow:   '0xEBCB8B'
      blue:     '0x81A1C1'
      magenta:  '0xB48EAD'
      cyan:     '0x8FBCBB'
      white:    '0xECEFF4'

  dracula: &dracula
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xbd93f9'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbbbbbb'
    bright:
      black:   '0x555555'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xcaa9fa'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xffffff'

colors: *dracula
window_opacity: 0.5
