format = """
${custom.success}\
${custom.error}\
[█](#32302f)\
[█](#3c3836)\
[█](#504945)\
[  ](bg:#665c54 fg:#d4be98)\
[](bg:#d4be98 fg:#665c54)\
$directory\
[](fg:#d4be98 bg:#665c54)\
$git_branch\
$git_status\
[](fg:#665c54 bg:#504945)\
$c\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#504945 bg:#3c3836)\
$time\
[ ](fg:#3c3836)\
\n$character
"""

[custom.success]
when = "test $status -eq 0"
format = '[╭─](#d4be98)'

[custom.error]
when = "test $status -ne 0"
format = '[╭─](#ea6962)'

[directory]
style = "fg:#504945 bg:#d4be98"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol $branch ](fg:#d4be98 bg:#665c54)]($style)'

[git_status]
style = "bg:#665c54"
format = '[[($all_status$ahead_behind )](fg:#d4be98 bg:#665c54)]($style)'

[c]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'
detect_extensions = ['cpp', 'c', 'h']

[python]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'

[nodejs]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'

[rust]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'

[golang]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'

[php]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol ($version) ](fg:#d4be98 bg:#504945)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3c3836"
format = '[[  $time ](fg:#a89984 bg:#3c3836)]($style)'

[character]
format = '$symbol '
success_symbol = '[╰─](#d4be98)'
error_symbol = '[╰─](#ea6962)'
